name: FastApi demo test

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.12

    - name: Install dependencies
      run: make install

    - name: Run format
      run: make format

    - name: Run lint
      run: make lint

    - name: Run test
      run: make test
